---
- hosts: localhost
  connection: local
  vars:
    container_count: 4
    default_container_name: RealTime Kafka App
    default_container_image: ubuntu
    default_container_command: sleep 1d
  tasks:
    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      community.docker.docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ container_count }}

